# Generated by Django 2.1.5 on 2019-03-12 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_events_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 12, 16, 4, 28, 752093, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
