# Generated by Django 2.1.5 on 2019-03-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190312_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(default='https://images.unsplash.com/photo-1516414559093-91c1c3d7359c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80', upload_to='cars'),
        ),
    ]
